### ISSUE TITLE
I cannot use Fleece in a .NET Core project

### ISSUE THREAD

**Issue by dzendras** [mausch/Fleece#37] opened 2018-08-16 08:39 UTC
I'd like to migrate my project to .NET Core.
It appears that Fleece is the showstopper. Do you have plans on becoming .NET Standard compatible?

Thanks,
Jedrek

**Comment by wallymathieu** [comment] 2018-08-16 17:03
Either try to use a version that supports it like the [Fleece.FSharpData](https://www.nuget.org/packages/Fleece.FSharpData/) version, or make a PR with an updated version of the dependency System.Json (they have removed parts of the API).

**Comment by wallymathieu** [comment] 2018-08-16 17:11
Looks like the fsharp data one needs to be upgraded to 3.0.0-beta* in order to be compatible with netstandard, so another bug.

**Comment by gusty** [comment] 2018-08-16 17:25
@dzendras 
I'm already using it in netstandard and no issues so far.
The first question is which distribution are you using? (System.Json/FSharp.Data/Newtonsoft)

**Comment by gusty** [comment] 2018-09-24 14:33
If there is no feedback on this, I would assume that it was a problem in the user side, and that it was resolved.

Otherwise, let me know and I will reopen.

**Comment by dzendras** [comment] 2018-09-24 14:37
I use the System.Json one.

**Comment by gusty** [comment] 2018-09-24 14:41
Reopening.

Can you pull the new System.Json version?
It was just merged today and we're planning to release it soon.

**Comment by dzendras** [comment] 2018-09-24 14:52
I'd rather wait for the official nuget package.
Thanks.

**Comment by gusty** [comment] 2018-09-27 06:10
@dzendras You can try now https://www.nuget.org/packages/Fleece.SystemJson/

**Comment by wallymathieu** [comment] 2018-10-29 17:17
Is this still an issue?

**Comment by dzendras** [comment] 2018-11-07 08:47
Hi! Sorry for the delay, but I didn't have time to test this yet. Will let you know shortly.

**Comment by wallymathieu** [comment] 2018-11-07 13:35
What namespaces/modules have you opened?

**Comment by dzendras** [comment] 2018-11-07 14:12
open Fleece
open Fleece.Operators
open FSharpPlus

**Comment by gusty** [comment] 2018-11-07 14:18
@dzendras We changed the namespace, as Fleece evolved to Json mapper for 3 different libraries (originally it was only System.Json).

So, now you'll have to change the first 2 open lines to:

    open Fleece.SystemJson
    open Fleece.SystemJson.Operators
    
That should be all you need.

**Comment by dzendras** [comment] 2018-11-07 14:45
Unfortunately not.

open Fleece.SystemJson
open Fleece.SystemJson.Operators
open FSharpPlus
open System.Json

and I'm getting loads of errors:

let metadata : FixtureEventMetadata ParseResult = metadata |> fromBytes |> parseJSON
    match metadata with
    | Success md -> { Event = evt; Metadata = md }
    | Failure x -> failwithf "Failed to deserialise: %s" x 

The pattern discriminator "Success" is not defined.

**Comment by gusty** [comment] 2018-11-07 14:49
OK, that solved the issue of the namespace, the other errors disappeared.

Now, just add an:

open Fleece.SystemJson.Helpers

Or just replace Success with Ok and Failure with Error as a quick check.

**Comment by dzendras** [comment] 2018-11-07 15:08
That helped a bit, but some errors are still present.

type Metadata with
    static member ToJSON(x : Metadata)=
        jobj [
            "Id" .= x.Id
            "Timestamp" .= x.Timestamp
        ]
    static member FromJSON(_: Metadata) =
        function
        | JObject o ->
            monad {
                let! fixtureId = o .@ "Id"
                let timestampJSON = match o.TryGetValue("Timestamp") with | true,ts -> ts | _ -> failwith "FOO"
                let! timestamp = fromJSON timestampJSON
                return { FixtureId = fixtureId; Timestamp = timestamp }

Results in tons of errors like:

Error	FS0193	Possible overload: 'static member FsControl.Core.TypeMethods.Applicative.Pure.instance : Pure:FsControl.Core.TypeMethods.Applicative.Pure * string -> (char -> string)'. Type constraint mismatch. The type 
    'Result<'a,string>'    
is not compatible with type
    'string'    

The errors differ by the incompatible types, to name a few: exn, Result<'b, string>

Thanks for your help guys, but the code will be abandoned soon, so I don't want to spend more time on it.

**Comment by gusty** [comment] 2018-11-07 15:19
How come that FsControl shows up in the errors?

I'm guessing that you're not recompiling all your projects.

Anyway, FsControl was merged into FSharpPlus years ago, so it looks like you have a really old code base.

I understand that if the code is going to be abandoned there's no need to spent an effort in migrating it.

On the other hand, if you want to go the path of .NET core, be prepared to upgrade tons of libraries, not just this one.

As there is no way to reproduce the error, I will close this issue.

Feel free to re-open if you have more information, also feel free to ask for help, if you decide to upgrade to the latest version, which despite the breaking changes (which are clearly documented in the release notes) has lots of exciting new features.

**Closed by gusty** 2018-11-07 15:19 UTC

**Comment by dzendras** [comment] 2018-11-07 15:23
Again, thanks for your help.
My codebase is indeed very old. I'm abandoning Fleece due to a different concern though - I won't need JSON support anymore.
